### ISSUE TITLE
NoSuchMethodError: Class 'bool' has no instance getter 'data'.

### ISSUE THREAD

**Issue by ghost** [rajayogan/flutterauth-MongoDB#3]
E/flutter ( 6664): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: Class 'bool' has no instance getter 'data'.
E/flutter ( 6664): Receiver: true
E/flutter ( 6664): Tried calling: data
E/flutter ( 6664): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 6664): #1      _LoginTestState.build.<anonymous closure>.<anonymous closure>
package:flutter_auth/…/Login/LoginTest.dart:40
E/flutter ( 6664): #2      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter ( 6664): #3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 6664): <asynchronous suspension>
E/flutter ( 6664):

**Comment by ghost** [comment]
Closed Issue , Service/authservice.dart needs to return response;
